### ISSUE TITLE
Präsentation 5 abhalten

### ISSUE THREAD

**Issue by Snipes09** [CodersbayJuniors2023/Issues_Wessely#13]

**Comment by PatrikVeliki** [comment]
Wann wird die stattfinden?

**Comment by Snipes09** [comment]
abgehalten am 25.11.2023

Frontend Besteller-Ansicht: mit Zeige Alle Artikel Button, Suchleiste und Suche-Button. Alles Funktionsfähig.
Frontend Warenkorb-Ansicht:  Liste mit Artikeln farblich getrennt. (Weiß und Hellgrau), bei Dropdownfenster Teamauswahl Designfehler.
